# Generated by Django 4.2.20 on 2025-04-25 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheettable',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='timesheet_app.project'),
        ),
    ]
