# Generated by Django 4.2.20 on 2025-05-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet_app', '0004_timesheet_status_timesheet_submission_date_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
