# Generated by Django 4.2.20 on 2025-06-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet_app', '0009_alter_team_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team',
            field=models.CharField(blank=True, choices=[('Search', 'Search Team'), ('Creative', 'Creative Team'), ('Development', 'Development Team')], max_length=50),
        ),
    ]
