# Generated by Django 4.2.20 on 2025-06-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet_app', '0010_alter_team_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='projects_assigned', to='timesheet_app.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='teams_assigned', to='timesheet_app.project'),
        ),
    ]
